[package]
name = "crabtrap"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
windows = { version = "0.58", features = ["Win32_System_Diagnostics_ToolHelp"] }
# [target.'cfg(windows)'.dependencies]



